# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required - version of RTD yaml
version: 2

# Python and additional requirements required to build your docs
python:
  version: 3.8
  install:
    - requirements: requirements.txt

# Builder
builder:
  image: stable

# Build documentation in the Projekt/ directory with Sphinx
sphinx:
  configuration: Projekt/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
